# Generated by Django 4.2.2 on 2023-07-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
        migrations.RemoveField(
            model_name='test',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.AddField(
            model_name='test',
            name='questions_list',
            field=models.CharField(default='test', max_length=1000000, verbose_name='Список'),
            preserve_default=False,
        ),
    ]
