# Generated by Django 4.2.2 on 2023-07-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_test_author_remove_test_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions_list',
            field=models.TextField(max_length=1000000, verbose_name='Список'),
        ),
    ]
