# Generated by Django 4.2.2 on 2023-07-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_test_questions_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questions_list',
        ),
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('Уникальный выбор', 'Уникальный выбор'), ('Множественный выбор', 'Множественный выбор')], max_length=50)),
                ('text', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.test')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
    ]
